site_name: healthcare.ai
site_url: http://healthcare.ai
repo_url: https://github.com/HealthCatalyst/healthcareai-py

theme: readthedocs
site_favicon: favicon.ico
docs_dir: docs

pages:
    - Introduction: index.md
    - Getting Started: getting_started.md
    - Profiling Your Data: profiling_your_data.md
    - Training, Comparing and Saving Models: training.md
    - Making Predictions and Deploying Models: deploy.md
    - Choosing a Prediction Output Type: prediction_types.md
    - Working With Other Databases: databases.md
    - Compiling Python Files To An Executable: compile.md
    - Utilities: utilities.md
    - Working With Healthcare.ai in a Health Catalyst EDW: catalyst_edw_instructions.md
    - Hints and Tips: hints.md
    - FAQ: FAQ.md
    - Architecture Overview For Developers: architecture_overview_for_developers.md

google_analytics: ['UA-85609357-1', 'auto']
